name: Build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

# Cancel in-progress runs for pull requests when developers push
# additional changes, and serialize builds in branches.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: linux-arm64
    runs-on: ubuntu-22.04-arm
    env:
      DISABLE_V8_COMPILE_CACHE: 1
      VERSION: 0.0.0
      VSCODE_TARGET: linux-arm64
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

    steps:
      - run: sudo apt update && sudo apt install -y libkrb5-dev
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # latest
        with:
          packages: quilt
          version: 1.0

      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: quilt push -a
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: |
            package-lock.json
            test/package-lock.json
      - run: SKIP_SUBMODULE_DEPS=1 npm ci
      - run: npm run build
      # Get Code's git hash. When this changes it means the content is
      # different and we need to rebuild.
      - name: Get latest lib/vscode rev
        id: vscode-rev
        run: echo "rev=$(git rev-parse HEAD:./lib/vscode)" >> $GITHUB_OUTPUT
      # We need to rebuild when we have a new version of Code, when any of the
      # patches changed, or when the code-server version changes (since it gets
      # embedded into the code). Use VSCODE_CACHE_VERSION to force a rebuild.
      - name: Fetch prebuilt linux-arm64 Code package from cache
        id: cache-vscode
        uses: actions/cache@v4
        with:
          path: lib/vscode-reh-web-linux-arm64
          key: vscode-linux-arm64-package-${{ secrets.VSCODE_CACHE_VERSION }}-${{ steps.vscode-rev.outputs.rev }}-${{ hashFiles('patches/*.diff', 'ci/build/build-vscode.sh') }}
      - name: Build vscode
        if: steps.cache-vscode.outputs.cache-hit != 'true'
        run: |
          pushd lib/vscode
          npm ci
          popd
          npm run build:vscode
      # Push up an artifact containing the linux-arm64 release.
      - run: KEEP_MODULES=1 npm run release
      - run: tar -czf package.tar.gz release
      - uses: actions/upload-artifact@v7
        with:
          name: linux-arm64-package
          path: ./package.tar.gz
